### ISSUE TITLE
Can we get code from C or Java

### ISSUE THREAD

**Issue by mrshanas** [vonshirco/cs_2#1]
Some of us we haven't studied C++.

**Comment by vonshirco** [comment]
Although you can use languages such as C, Java, C++ etc.

I recommend using C++ because of good optimization, works quick and fine.

You do not have to have advanced knowledge of C++ to get started, basics of C++ is enough and if you have a good foundation of C language then you are good to go 👍.

**Comment by mrshanas** [comment]
Some resources links will be helpful
